apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: back
    spec:
      containers:
        - name: mern-k8s-back
          image: andresmunguia/mern-k8s-back
          ports: 
            - containerPort: 5000
          env: 
            - name: PORT
              value: "5000"
            - name: CONN_STR
              value: "mongodb+srv://mern-k8s:mern-k8s@mern-k8s.gci7rew.mongodb.net/?retryWrites=true&w=majority"